# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PowerMat <- function(tempMat, power) {
    .Call(`_simesHotelling_PowerMat`, tempMat, power)
}

colMeanRcpp <- function(X) {
    .Call(`_simesHotelling_colMeanRcpp`, X)
}

CovFind <- function(X) {
    .Call(`_simesHotelling_CovFind`, X)
}

MahalanobisArma <- function(x, center, cov) {
    .Call(`_simesHotelling_MahalanobisArma`, x, center, cov)
}

RandomHoteling <- function(x, center, cov, n, samp_size) {
    .Call(`_simesHotelling_RandomHoteling`, x, center, cov, n, samp_size)
}

IndHoteling <- function(x, center, cov, samp_mat) {
    .Call(`_simesHotelling_IndHoteling`, x, center, cov, samp_mat)
}

CombineVectors <- function(vec_1, num) {
    .Call(`_simesHotelling_CombineVectors`, vec_1, num)
}

HotelingFind <- function(selected, not_select, x, center, cov) {
    .Call(`_simesHotelling_HotelingFind`, selected, not_select, x, center, cov)
}

CreateSol <- function(x, center, cov, group_vector) {
    .Call(`_simesHotelling_CreateSol`, x, center, cov, group_vector)
}

pMatMaker <- function(statMat) {
    .Call(`_simesHotelling_pMatMaker`, statMat)
}

FreedomDegreeFind <- function(covX, covY, nX, nY) {
    .Call(`_simesHotelling_FreedomDegreeFind`, covX, covY, nX, nY)
}

HotelingCalc <- function(X, Y, center) {
    .Call(`_simesHotelling_HotelingCalc`, X, Y, center)
}

HotelingNonEqual <- function(X, Y, samp_mat, center) {
    .Call(`_simesHotelling_HotelingNonEqual`, X, Y, samp_mat, center)
}

